project: mlp

# Dataset settings
dataset:
  dir: /home/blkdmr/projects/deepl-starter/dataset/mnist.csv

# Training configuration
training:
  seed: 42
  epochs: 10
  learning_rate: 1e-4
  weight_decay: 1e-2
  train_batch: 32
  test_batch: 32
  device: cuda

# Logging
logger:
  dir: logging
  use_wandb: False

# Weights & Biases configuration
#wandb:
#  key:
#  entity: